apiVersion: v1
kind: Service
metadata:
  name: earth-map-service

spec:
  type: NodePort
  clusterIP: "10.96.0.100"
  externalTrafficPolicy: Local
  selector:
    app: earth-map
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



