apiVersion: v1
kind: Service
metadata:
  name: map-service

spec:
  type: NodePort
  clusterIP: 10.96.0.20
  externalTrafficPolicy: Local
  selector:
    app: volcanoes-map
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



