apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

nodeGroups:
- name: demo-ng
  instanceType: t2.small
  desiredCapacity: 2
  minSize: 1
  maxSize: 5
  ssh:
    publicKeyName: eks
cloudWatch:
  clusterLogging:
    enableTypes:
    - "api"
    - "audit"
    - "controllerManager"
availabilityZones: ['us-east-1a', 'us-east-1b']
