apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ClusterAdmin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cluster-admin-binding
subjects:
- kind: User
  name: kubadmin
  apiGroup: "rbac.authorization.k8s.io"
roleRef: 
  kind: ClusterRole
  name: ClusterAdmin
  apiGroup: "rbac.authorization.k8s.io"
